<?xml version="1.0"?>
<package format="3">
  <name>ur10_perception</name>
  <version>0.0.1</version>
  <description>UR10 perception-aware energy-efficient trajectory planning</description>
  <maintainer email="ali@example.com">ali</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>control_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
